# Generated by Django 3.2.25 on 2024-08-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../profiles/images/nobody.jpg', upload_to='image/'),
        ),
    ]
