# Generated by Django 3.2.25 on 2024-08-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='images',
            field=models.ImageField(blank=True, default='../profiles/images/nobody.jpg', upload_to='image/'),
        ),
    ]
