# Generated by Django 5.1 on 2024-08-28 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
